server:
  port: 0

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations:
            - classpath:config/core/{application}
            - classpath:config/stat/{application}
            - classpath:config/infra/{application}


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/