server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5437/user_db
    username: dbuser
    password: 12345
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql