server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # ✅ Автоматическое определение сервисов из Eureka

      routes:
        # === USER SERVICE ===
        - id: user-service-admin
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

        # === REQUEST SERVICE ===
        - id: request-service
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/requests/**
        - id: request-service
          uri: lb://request-service
          predicates:
            - Path=/users/{userId}/events/{eventId}/requests
        # === COMMENT SERVICE ===
        - id: comment-service-admin
          uri: lb://comment-service
          predicates:
            - Path=/admin/comments/**
        - id: comment-service-user
          uri: lb://comment-service
          predicates:
            - Path=/users/{userId}/comments/**
        - id: comment-service-public
          uri: lb://comment-service
          predicates:
            - Path=/comments/**

        # === EVENT SERVICE ===
        - id: event-service-admin
          uri: lb://event-service
          predicates:
            - Path=/admin/events/**
        - id: event-service-private
          uri: lb://event-service
          predicates:
            - Path=/users/{userId}/events/**
        - id: event-service-public
          uri: lb://event-service
          predicates:
            - Path=/events/**, /categories/**, /compilations/**
        - id: categories-admin-service
          uri: lb://event-service
          predicates:
            - Path=/admin/categories/**
        - id: compilation-admin-service
          uri: lb://event-service
          predicates:
            - Path=/admin/compilations/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
